service: gianini-app-ser-dev

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  deploymentBucket:
    blockPublicAccess: true # Prevents public access via ACLs or bucket policies. Default is false
    name: zappa-gianini-service

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: gianini-app-ser-dev
    handler: app.app
    description: gianini-app-ser-dev
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"
